name: dogs_yaml
description: Yaml serializer for the dogs graph serializer
version: 2.0.16
repository: https://github.com/DarwinFramework/dogs

environment:
  sdk: '>=2.18.6 <3.0.0'

dependencies:
  dogs_core: ^6.0.0
  yaml: ^3.1.1
  json2yaml: ^3.0.0

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
