name: dogs_project
repository: https://github.com/DarwinFramework/dogs
packages:
  - packages/**
  - example/
  - benchmarks/
scripts:
  copy-readme:
    name: copy-readme
    description: 'Copies the root-Readme to the dogs package'
    run: cp README.md packages/dogs/README.md
  analyze:
    name: analyze
    description: 'Runs the dart analyzer'
    run: dart analyze .
    exec:
      concurrency: 1
  format:
    name: format
    description: 'Runs the dart formatter'
    run: dart format .
    exec:
      concurrency: 1
  smoke:
    name: smoke
    description: 'Runs smoke tests'
    run: cd smoke/ && bash smoke.sh && cd ../
  test:
    description: Run tests in a specific package.
    run: dart test test/*
    exec:
      concurrency: 1
    packageFilters:
      dirExists:
        - test