site_name: Dart Object Graphs

theme:
  name: material
  palette:
    primary: indigo
    scheme: slate
  features:
    - content.code.copy
    - content.tabs.link
    - navigation.indexes
    - navigation.path
    - navigation.sections
    - attr_list

extra_css:
  - stylesheets/extra.css

nav:
  - start.md
  - installation.md
  - "Getting Started":
      - serializables.md
      - serialization.md
      - projection.md
      - validation.md
      - polymorphism.md
      - converters.md
  - "Advanced Concepts":
      - advanced/structures.md
      - advanced/annotations.md
      - advanced/operation_modes.md
      - advanced/tree_converters.md
  - "Database Support (ODM)":
        - odm/start.md
        - odm/query_dsl.md
  - "Official Packages":
      - "Built [dogs_built]":
          - built/index.md
          - built/start.md
      - "Forms [dogs_forms]":
          - forms/index.md
          - forms/start.md
          - forms/customization.md
          - forms/translation.md
      - "Firestore [dogs_firestore]":
          - firestore/index.md
          - firestore/start.md
          - firestore/queries.md
          - firestore/subcollections.md
          - firestore/mappings.md
markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.mark
  - pymdownx.tabbed:
      alternate_style: true
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format