site_name: Dart Object Graphs

theme:
  name: material
  palette:
    primary: indigo
    scheme: slate
  features:
    - content.code.copy
    - content.tabs.link

nav:
  - index.md
  - serializables.md
  - serialization.md
  - projection.md
  - validation.md
  - Advanced:
    - advanced/structures.md
    - advanced/annotations.md

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.mark
  - pymdownx.tabbed:
      alternate_style: true
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format