name: dogs_project
repository: https://github.com/DarwinFramework/dogs

environment:
  sdk: '>=3.9.0 <4.0.0'

dev_dependencies:
  melos: ^7.0.0

workspace:
  - packages/dogs_core
  - packages/dogs_generator
  - packages/dogs_flutter
  - packages/dogs_built
  - packages/dogs_firestore
  - formats/dogs_cbor
  - formats/dogs_toml
  - formats/dogs_yaml

melos:
  scripts:
    copy-readme:
      name: copy-readme
      description: 'Copies the root-Readme to the dogs package'
      run: cp README.md packages/dogs/README.md
    analyze:
      name: analyze
      description: 'Runs the dart analyzer'
      run: dart analyze .
      exec:
        concurrency: 1
      packageFilters:
        ignore:
          - "benchmarks"
    format:
      name: format
      description: 'Runs the dart formatter'
      run: dart format .
      exec:
        concurrency: 1
    smoke:
      name: smoke
      description: 'Runs smoke tests'
      run: cd smoke/ && bash smoke.sh && cd ../
      packageFilters:
        ignore:
          - "*mongo*"
    deploy-pages:
      exec:
        concurrency: 1
      run: bash page-deploy.sh
      packageFilters:
        fileExists:
          - page-deploy.sh
    preview-docs:
      description: 'Runs the preview docs script'
      run: "bash .github/workflows/scripts/prepare-demo-build.sh && mkdocs serve"
    test:
      description: Runs all tests in the project.
      run: melos test-dart && melos test-flutter
    test-dart:
      description: Run dart tests in a specific package.
      run: dart test test/*
      exec:
        concurrency: 1
      packageFilters:
        flutter: false
        ignore:
          - "*mongo*"
        dirExists:
          - test
    test-flutter:
      description: Run flutter tests in a specific package.
      run: flutter test test/*
      exec:
        concurrency: 1
      packageFilters:
        flutter: true
        dirExists:
          - test