name: dogs_flutter
description: "Flutter support for the dogs_core package"
version: 0.0.1-dev.12
repository: https://github.com/helightdev/dogs

environment:
  sdk: ^3.9.0
  flutter: ">=3.35.2"

resolution: workspace

dependencies:
  flutter:
    sdk: flutter
  dogs_core: ^10.1.1
  lyell: ^1.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  dogs_generator: ^7.1.0
  build_runner: ^2.4.15

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter: {}

dogs:
  library: true