name: dogs_built
description: Adds a basic interop for built_value serializers to dogs_core.
version: 3.1.5-dev.5
repository: https://github.com/DarwinFramework/dogs

environment:
  sdk: '>=3.5.0 <4.0.0'

resolution: workspace

dependencies:
  built_collection: ^5.1.1
  built_value: ^8.6.2
  dogs_core: ^10.0.0-dev.5

dev_dependencies:
  lints: ^5.1.1
  test: ^1.25.9
