name: smoke_mongo
description: A sample command-line application.
version: 1.0.0
publish_to: none

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  logging: '>=1.1.0 <1.2.0'
  lyell: ^1.1.0
  dogs_core: any
  dogs_built: any
  dogs_odm: any
  dogs_mongo_driver: any

dev_dependencies:
  build_runner: any
  dogs_generator: any

  lints: ^2.0.1
  test: ^1.23.1
