name: Bug Report
description: Report a bug
title: '[Bug] '
labels: [ 'bug' ]
assignees:
  - helightdev
body:
  - type: dropdown
    id: affected_package
    attributes:
      label: Affected Package
      description: Select the package where you encountered the bug.
      multiple: true
      options:
        - dogs_core
        - dogs_generator
        - dogs_flutter
        - dogs_yaml
        - dogs_toml
        - dogs_cbor
        - dogs_built
        - dogs_firestore
    validations:
      required: true
  - type: textarea
    id: description
    attributes:
      label: Description
      description: Provide a clear and concise description of the bug.
      placeholder: "A clear and concise description of what the bug is."
    validations:
      required: true
  - type: textarea
    id: steps_to_reproduce
    attributes:
      label: Steps to Reproduce
      description: List the steps to reproduce the behavior.
      placeholder: |
        1. Go to '...'
        2. Click on '....'
        3. Scroll down to '....'
        4. See error
    validations:
      required: false
  - type: textarea
    id: expected_behavior
    attributes:
      label: Expected Behavior
      description: Describe what you expected to happen.
      placeholder: "A clear and concise description of what you expected to happen."
    validations:
      required: false
  - type: textarea
    id: additional_context
    attributes:
      label: Additional Context
      description: Add any other context about the problem here.
      placeholder: "Add any other context about the problem here."
    validations:
      required: false