name: dogs_cbor
description: Cbor serializer for the dogs graph serializer
version: 2.3.5-dev.4
repository: https://github.com/DarwinFramework/dogs

environment:
  sdk: '>=3.5.0 <4.0.0'

resolution: workspace

dependencies:
  cbor: ^5.1.2
  dogs_core: ^10.0.0-dev.4

dev_dependencies:
  lints: ^5.1.1
  test: ^1.25.9
