name: dogs_toml
description: Toml serializer for the dogs graph serializer
version: 2.0.30
repository: https://github.com/DarwinFramework/dogs

environment:
  sdk: '>=2.18.6 <4.0.0'

dependencies:
  dogs_core: ^8.0.2
  toml: ^0.15.0

dev_dependencies:
  lints: ^2.0.1
  test: ^1.23.1
