name: dogs_toml
description: Toml serializer for the dogs graph serializer
version: 2.3.5-dev.4
repository: https://github.com/DarwinFramework/dogs

environment:
  sdk: '>=3.5.0 <4.0.0'

resolution: workspace

dependencies:
  dogs_core: ^10.0.0-dev.4
  toml: ^0.15.0

dev_dependencies:
  lints: ^5.1.1
  test: ^1.25.9
