name: dogs_core
description: universal object mapping and serialization library with a focus on dx.
version: 10.0.0-dev.7
repository: https://github.com/helightdev/dogs
documentation: https://dogs.helight.dev
issue_tracker: https://github.com/helightdev/dogs/issues

topics:
  - serialization
  - dataclass
  - json
  - orm

environment:
  sdk: '>=3.5.0 <4.0.0'

resolution: workspace

dependencies:
  collection: ^1.19.1
  crypto: ^3.0.6
  lyell: ^1.4.3
  meta: ^1.16.0

dev_dependencies:
  lints: ^5.1.1
  test: ^1.25.9
