name: smoke_test_1
description: A sample command-line application.
version: 1.0.0
publish_to: none

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  logging: ^1.3.0
  lyell: ^1.1.0
  dogs_core: any
  dogs_built: any
  built_collection: ^5.1.1
  built_value: ^8.11.1

dev_dependencies:
  build_runner: any
  dogs_generator: any
  built_value_generator: ^8.11.1

  lints: ^2.0.1
  test: ^1.23.1
