name: smoke_test_1
description: A sample command-line application.
version: 1.0.0
publish_to: none

environment:
  sdk: '>=2.18.2 <3.0.0'

dependencies:
  logging: '>=1.1.0 <1.2.0'
  lyell: ^1.1.0
  dogs_core: any
  dogs_built: any
  built_collection: ^5.1.1
  built_value: ^8.6.2

dev_dependencies:
  build_runner: any
  dogs_generator: any
  built_value_generator: ^8.6.2

  lints: ^2.0.1
  test: ^1.23.1
