name: dogs_mongo_driver
description: MongoDB driver for dogs_orm
version: 1.0.0-alpha.18

environment:
  sdk: ^3.0.0

dependencies:
  # path: ^1.8.0
  dogs_core: ^10.0.0-dev.1
  dogs_odm: ^1.0.0-alpha.18
  mongo_dart: ^0.10.0
  fixnum: ^1.1.0
  decimal: ^2.3.3

dev_dependencies:
  lints: ^2.1.0
  test: ^1.24.0
