name: dogs_odm
description: Odm support for dogs.
version: 1.0.0-alpha.1
# repository: https://github.com/my_org/my_repo

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  dogs_core: ^8.1.1
  collection: ^1.18.0
  meta: ^1.11.0
  uuid: ^4.3.3

dev_dependencies:
  lints: ^3.0.0
  test: ^1.25.1