/*
 *    Copyright 2022, the DOGs authors
 *
 *    Licensed under the Apache License, Version 2.0 (the "License");
 *    you may not use this file except in compliance with the License.
 *    You may obtain a copy of the License at
 *
 *        http://www.apache.org/licenses/LICENSE-2.0
 *
 *    Unless required by applicable law or agreed to in writing, software
 *    distributed under the License is distributed on an "AS IS" BASIS,
 *    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *    See the License for the specific language governing permissions and
 *    limitations under the License.
 */

import "package:dogs_core/dogs_core.dart";
import "package:meta/meta.dart";

/// Base class for converters used by the [DogEngine].
/// Contains structure information about the type being serialized and provides
/// an [OperationMode] mapping for all supported operation modes.
abstract class DogConverter<T> extends TypeCapture<T> {
  /// If the converter is associated with the type [T].
  /// Used by the [DogEngine.registerAutomatic] to determine if a converter
  /// should be automatically registered to [T].
  final bool isAssociated;

  /// If the converter should keep iterables as iterables or convert them
  /// automatically if they occur inside a [DogStructure].
  final bool keepIterables;

  /// The [DogStructure] associated with this converter and the type [T].
  final DogStructure<T>? struct;

  /// Base class for converters used by the [DogEngine].
  /// Contains structure information about the type being serialized and provides
  /// an [OperationMode] mapping for all supported operation modes.
  const DogConverter(
      {this.struct,
      this.isAssociated = true,
      @Deprecated(
          "This parameter has been removed in favor of the shift towards tree based converters. "
          "This value is effectively a no-op, please remove it.")
      this.keepIterables = false});

  /// Returns the operation mode for the given [opmodeType] or null if the
  /// converter does not support the given operation mode by default.
  OperationMode<T>? resolveOperationMode(DogEngine engine, Type opmodeType) =>
      null;

  /// Generates a [SchemaType] describing the output generated by this converter.
  ///
  /// NOTE: Do not return a shared instance of [SchemaType] as it will be modified by the
  /// visitor. For such cases, use [SchemaType.clone] to create a new instance.
  SchemaType describeOutput(DogEngine engine, SchemaConfig config) =>
      SchemaType.any;
}

// TODO: Future replacement for @serializable
/// Configures the dogs structuration of a class or enum.
class Structure extends Serializable implements StructureMetadata {
  /// If the type is serializable.
  final bool serializable;

  /// Configures the dogs structuration of a class or enum.
  const Structure({this.serializable = false, super.serialName});
}

/// See @[serializable].
class Serializable {
  /// The name of the type used for serialization.
  final String? serialName;

  /// See @[serializable].
  const Serializable({this.serialName});
}

/// Marks a library import as dogs serializable.
///
/// All types defined inside or exported by the library will be considered
/// serializable. The [include] and [exclude] parameters can be used to
/// further restrict the set of serializable types.
///
/// Types that semantically match a structure conformity or compatibility check must also be
/// correct, invalid items will not be skipped but throw an exception. You must explicitly exclude
/// types that are not serializable using the [exclude] parameter, or only include types that are
/// serializable using the [include] parameter.
///
/// For built_value types, the not serializable builder will automatically be excluded, but will be
/// used for the generation of the actual type converter.
class SerializableLibrary {
  /// A list of regex patterns that match the type identifiers to include in the serialization.
  final List<String>? include;

  /// A list of regex patterns that match the type identifiers to exclude from the serialization.
  final List<String>? exclude;

  /// see @[SerializableLibrary].
  const SerializableLibrary({this.include, this.exclude});
}

/// Marks a class or enum as serializable.
const serializable = Structure(serializable: true);

@internal
class LinkSerializer {
  const LinkSerializer();
}

/// Manually marks a custom dog converter implementation for linking.
/// The dogs_generator will then include an instance of this converter.
const linkSerializer = LinkSerializer();

/// Supplier function for default values.
typedef DefaultValueSupplier = dynamic Function();

class _BeanIgnore {
  const _BeanIgnore();
}

/// Marks a property as ignored when using the bean conformity.
const beanIgnore = _BeanIgnore();

/// Marks a property as polymorphic, meaning its values type can vary.
class _Polymorphic extends StructureMetadata {
  const _Polymorphic();
}

/// Marks a property as polymorphic, meaning its value's type can vary.
const polymorphic = _Polymorphic();

@internal

/// Checks if a field is marked as polymorphic.
bool isPolymorphicField(DogStructureField field) {
  return field.annotationsOf<_Polymorphic>().isNotEmpty;
}

/// Overrides the name that will be used by the [GeneratedDogConverter] for this
/// specific property. By default, the field name will be used.
class PropertyName {
  /// The name of the property used as a map key in serialization.
  final String name;

  /// Instantiates a new [PropertyName] with the given [name].
  const PropertyName(this.name);
}

/// Overrides the serializer that will be used by the [GeneratedDogConverter]
/// for this specific property. By default, the field will be serialized using
/// the convert associated with its type.
class PropertySerializer {
  /// The type of the serializer.
  final Type type;

  /// Instantiates a new [PropertySerializer] with the given [type].
  const PropertySerializer(this.type);
}

/// Configures how the [GeneratedEnumDogConverter] will serialize this individual
/// enum value. The name can be overridden by specifying a [name]. This enum
/// value can also be marked as the fallback value.
class EnumProperty {

  /// The name of the enum value used as a map key in serialization.
  final String? name;

  /// If this enum value should be used as a fallback value when an invalid
  /// value is encountered during deserialization.
  final bool fallback;

  /// Instantiates a new [EnumProperty] with the given [name] and [fallback].
  const EnumProperty({this.name, this.fallback = false});
}

/// Simple converter base that only requires a [serialize] and [deserialize]
/// method. Automatically adds [NativeSerializerMode] as well as a synthetic
/// [DogStructure] with the given [SimpleDogConverter.serialName].
abstract class SimpleDogConverter<T> extends DogConverter<T>
    with OperationMapMixin<T> {
  /// Instantiates a new [SimpleDogConverter] with the given [serialName].
  /// Specify the [serialName] using `: super(serialName: "")`.
  SimpleDogConverter({required String serialName})
      : super(struct: DogStructure<T>.synthetic(serialName));

  @override
  Map<Type, OperationMode<T> Function()> get modes => {
        NativeSerializerMode: () => NativeSerializerMode.create(
            serializer: (value, engine) => serialize(value, engine),
            deserializer: (value, engine) => deserialize(value, engine)),
      };

  /// Serializes the given [value] to a [DogNativeCodec] native value.
  dynamic serialize(T value, DogEngine engine);

  /// Deserializes the given [value] from a [DogNativeCodec] native value.
  T deserialize(dynamic value, DogEngine engine);
}
