name: smoke_test_0
description: A sample command-line application.
version: 1.0.0
publish_to: none

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  logging: ^1.3.0
  lyell: ^1.1.0
  test: ^1.25.15
  dogs_core: any
  dogs_yaml:
    path: ../../formats/dogs_yaml
  dogs_cbor:
    path: ../../formats/dogs_cbor
  dogs_toml:
    path: ../../formats/dogs_toml

dev_dependencies:
  build_runner: any
  dogs_generator: any

  lints: ^3.0.0
