name: smoke_test_0
description: A sample command-line application.
version: 1.0.0
publish_to: none

environment:
  sdk: '>=2.18.2 <3.0.0'

dependencies:
  logging: '>=1.1.0 <1.2.0'
  lyell: ^1.1.0
  dogs_core: any
  dogs_yaml:
    path: ../../packages/dogs_yaml
  dogs_cbor:
    path: ../../packages/dogs_cbor
  dogs_toml:
    path: ../../packages/dogs_toml

dev_dependencies:
  build_runner: any
  dogs_generator: any

  lints: ^2.0.1
  test: ^1.23.1
