name: dogs_yaml
description: Yaml serializer for the dogs graph serializer
version: 2.3.1
repository: https://github.com/DarwinFramework/dogs

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  dogs_core: ^9.2.0
  yaml: ^3.1.2
  json2yaml: ^3.0.1

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
