name: benchmarks
description: A sample command-line application.
version: 1.0.0
publish_to: none

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  path: ^1.8.0
  dogs_core: ^10.0.0-dev.2
  dogs_yaml: ^2.3.5-dev.2
  dogs_cbor: ^2.3.5-dev.2
  dogs_toml: ^2.3.5-dev.2
  aqueduct_isolates: 1.0.1
  equatable: ^2.0.5
  mock_data: ^2.0.0

  built_collection: ^5.1.1
  built_value: ^8.9.5
  dart_mappable: ^4.4.0
  json_annotation: ^4.9.0
  freezed_annotation: ^3.0.0


  vm_service: ^14.0.0

dev_dependencies:
  build_runner: any
  lints: ^5.1.1
  test: ^1.25.15

  dogs_generator: ^7.0.0-dev.2
  build_web_compilers: any
  built_value_generator: ^8.9.5
  dart_mappable_builder: ^4.4.0
  json_serializable: ^6.9.4
  freezed: ^3.0.3

dogs:
  library: false