name: benchmarks
description: A sample command-line application.
version: 1.0.0
publish_to: none

environment:
  sdk: '>=2.19.6 <3.0.0'

dependencies:
  path: ^1.8.0
  dogs_core: ^7.2.2
  dogs_yaml: ^2.0.27
  dogs_cbor: ^2.0.27
  dogs_toml: ^2.0.27
  aqueduct_isolates: 1.0.1
  equatable: ^2.0.5
  mock_data: ^2.0.0

  built_collection: ^5.0.0
  built_value: ^8.4.0

dev_dependencies:
  build_runner: any
  lints: ^2.0.0
  test: ^1.16.0

  dogs_generator: ^5.0.13
  build_web_compilers: any
  built_value_generator: ^8.4.4

dogs:
  library: false